version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: database_mysql
    environment:
      MYSQL_DATABASE: notes_db
      MYSQL_ROOT_PASSWORD: 12345678
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
